#
#    WhatsApp Chat Browser
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

import re
import html
import datetime

if __package__ == "wacb":
    from . import wacbchat
    from . import wacbimg
    from . import wacbcss
    from . import wacbemoji
else:
    import wacbchat
    import wacbimg
    import wacbcss
    import wacbemoji

class WacbHtmlFormatter:
    cssUrl = "wacb.css"
    lineTerminator = "\n"
    # Matches URLs, _italics_ and *bold* formatting.
    regexForFmt = re.compile("(?:(_|\\*)([\\w\\s\\.]+)\\1)|(https?://[^\\s]+)")
    regexForFileName = re.compile("/?([0-9]{4})-?([0-9]{2})?\\.html")

    def __init__(self, messageContainer):
        self.messageContainer = messageContainer
        self.me = None
        self.css = None
        self.userNameMap = dict()
        self.imageWidth = 0
        self.imageWidth = 0
        self.emojifier = None
        self.title = None
        self.inlineImages = False
        self.inlineVideo = False
        self.inlineAudio = False
        self.formatForYear = "%Y"
        self.formatForMonth = "%B"
        self.formatForDay = "%B %d, %Y"
        self.linkedAttachments = set()
        self.linkedEmojis = set()
        self.configure(dict())

    def configure(self, configData):
        self.config = configData

        if "inlineImages" in self.config:
            self.inlineImages = self.config["inlineImages"]
        if "inlineVideo" in self.config:
            self.inlineVideo = self.config["inlineVideo"]
        if "inlineAudio" in self.config:
            self.inlineAudio = self.config["inlineAudio"]
        if "formatForYear" in self.config:
            self.formatForYear = self.config["formatForYear"]
        if "formatForMonth" in self.config:
            self.formatForMonth = self.config["formatForMonth"]
        if "formatForDay" in self.config:
            self.formatForDay = self.config["formatForDay"]
            
        if ("cssFileName" in self.config) and ("builtinCss" in self.config):
            self.css = wacbcss.makeCssProvider(self.config["cssFileName"], self.config["builtinCss"])
        else:
            self.css = None

        imageWidthFromCss = self.getParameterFromCssOrNone("inlineImage", "max-width")
        imageHeightFromCss = self.getParameterFromCssOrNone("inlineImage", "max-height")
        if imageWidthFromCss and imageHeightFromCss:
            self.imageWidth = int(imageWidthFromCss.rstrip("px"))
            self.imageHeight = int(imageHeightFromCss.rstrip("px"))

    def configureMe(self, me):
        self.me = self.messageContainer.users.find(me)

    def configureUserMap(self, userMap):
        for name, alias in userMap.items():
            user = self.messageContainer.users.find(name)
            if user and (len(alias) > 0):
                self.userNameMap[user] = alias

    def configureTitle(self, title):
        self.title = title

    def configureEmojifier(self, emojifier):
        self.emojifier = emojifier

    def getParameterFromCssOrNone(self, element, parameter):
        if self.css:
            if element in self.css:
                if parameter in self.css[element]:
                    return self.css[element][parameter]
        return None

    def joinLines(lines):
        result = ""
        for line in lines:
            result += line
            result += WacbHtmlFormatter.lineTerminator
        return result

    def htmlHeader(self):
        headerLines = [
            "<!DOCTYPE html>"
            "<html>",
            "<head>"
        ]

        if self.css:
            headerLines.append("<link rel=\"stylesheet\" href=\"{0}\">".format(WacbHtmlFormatter.cssUrl))

        if self.title:
            headerLines.append("<title>{0}</title>".format(html.escape(self.title)))

        headerLines.extend([
            "</head>",
            "<body>"
        ])
        return WacbHtmlFormatter.joinLines(headerLines)

    def htmlFooter(self):
        now = datetime.datetime.now()
        timestamp = now.isoformat(" ", "seconds")

        footerLines = [
            "<hr>"
            "<div class=\"message\">",
            "<div class=\"systemMessage\">",
            "Generated by WhatsAppChatBrowser at " + timestamp + ".",
            "</div>",
            "</div>",
            "</body>",
            "</html>"
        ]
        return WacbHtmlFormatter.joinLines(footerLines)

    def isMyMessage(self, message):
        return message.user == self.me

    def getMsgClass(self, message):
        return "userMessage-Me" if self.isMyMessage(message) else "userMessage-Them"

    def senderId(self, message):
        #
        # Do not print sender id if:
        # - There are only two participants in the chat, and we are one of them.
        # - There are more than two participants in the chat and the message is
        #   mine.
        #

        htmlLines = []
        twoPersonChat = self.me and len(self.messageContainer.users) <= 2
        isMyMessage = self.isMyMessage(message)
        noSenderId = twoPersonChat or isMyMessage

        if not noSenderId:
            if message.user:
                senderName = self.userNameMap[message.user] if message.user in self.userNameMap else str(message.user)
                htmlLines.append("<span class=\"senderName\">" + senderName + "</span><br>")

        return WacbHtmlFormatter.joinLines(htmlLines)

    def emojify(self, text):
        if not self.emojifier:
            return html.escape(text)
        emojifiedText = ""
        parsePos = 0
        emojifyMatch = self.emojifier.find(text)
        haveRegularText = False
        while emojifyMatch:
            if parsePos != emojifyMatch.pos:
                emojifiedText += html.escape(text[parsePos:emojifyMatch.pos], False)
                haveRegularText = True
            if self.emojifier.inline:
                imageType = emojifyMatch.emoji.type
                imageData = emojifyMatch.emoji.base64
                emojifiedText += "<img class=\"{class}\" src=\"data:" + imageType + ";base64," + imageData + "\">"
            else:
                imageUrl = self.emojifier.url(emojifyMatch.emoji)
                emojifiedText += "<img class=\"{class}\" src=\"" + imageUrl + "\">"
                self.linkedEmojis.add(emojifyMatch.emoji)
            parsePos = emojifyMatch.end
            emojifyMatch = self.emojifier.find(text, parsePos)
        if parsePos < len(text):
            emojifiedText += html.escape(text[parsePos:], False)
            haveRegularText = True
        emojiClass = "inlineEmoji" if haveRegularText else "standaloneEmoji"
        return emojifiedText.replace("{class}", emojiClass)

    #
    # Format message content.
    # - Replace URLs in a message text with links to that URL.
    # - Apply _italics_ and *bold* formatting.
    # - Replace unicode emojis with inline images, if desired.
    # - Replace the reserved '&', '<', '>' characters with HTML-safe sequences.
    # - Replace newlines with <br>.
    #

    def formatMessageText(self, text):
        formattedText = ""
        parsePos = 0
        fmtMatch = WacbHtmlFormatter.regexForFmt.search(text, parsePos)
        while fmtMatch:
            textBeforeMatch = text[parsePos:fmtMatch.start()]
            formattedText += self.emojify(textBeforeMatch)
            if fmtMatch[1] and fmtMatch[1] == '_':
                formattedText += "<i>" + html.escape(fmtMatch[2]) + "</i>"
            elif fmtMatch[1] and fmtMatch[1] == '*':
                formattedText += "<b>" + html.escape(fmtMatch[0][1:-1]) + "</b>"
            elif fmtMatch[3]:
                formattedText += "<a href=\"{0}\">{0}</a>".format(fmtMatch[3])
            parsePos = fmtMatch.end()
            fmtMatch = WacbHtmlFormatter.regexForFmt.search(text, parsePos)
        formattedText += self.emojify(text[parsePos:])
        return formattedText.replace("\n", "<br>")

    def formatRegularUserMessage(self, message):
        return self.formatMessageText(message.text)

    def scaleImage(self, width, height):
        if self.imageWidth != 0 and self.imageHeight != 0:
            if width > self.imageWidth or height > self.imageHeight:
                widthScale = width / self.imageWidth
                heightScale = height / self.imageHeight
                scale = max(widthScale, heightScale)
                width = int(width / scale)
                height = int(height / scale)
        return width, height

    def formatImageAttachmentMessage(self, message):
        with self.messageContainer.openFile(message.attachment) as imageFile:
            imageWidth, imageHeight = wacbimg.ImageHelper.getImageSizeFromFile(imageFile)

        if imageWidth:
            imageWidth, imageHeight = self.scaleImage(imageWidth, imageHeight)

            htmlLines = [
                "<a href=\"" + message.attachment + "\">",
                "<img class=\"inlineImage\" width=\"{0}\" height=\"{1}\" src=\"{2}\">".format(imageWidth, imageHeight, message.attachment),
                "</a>"
            ]
        else:
            htmlLines = [
                "<img class=\"inlineImage\" src=\"" + message.attachment + "\">",
            ]

        return WacbHtmlFormatter.joinLines(htmlLines)

    def formatVideoAttachmentMessage(self, message):
        htmlLines = [
            "<video controls=\"\">",
            "<source src=\"" + message.attachment + "\">",
            "<a href=\"{0}\">{0}</a>".format(message.attachment),
            "</video>"
        ]
        return WacbHtmlFormatter.joinLines(htmlLines)

    def formatAudioAttachmentMessage(self, message):
        htmlLines = [
            "<audio controls=\"\">",
            "<source src=\"" + message.attachment + "\">",
            "<a href=\"{0}\">{0}</a>".format(message.attachment),
            "</audio>"
        ]
        return WacbHtmlFormatter.joinLines(htmlLines)

    def formatGenericAttachmentMessage(self, message):
        htmlLines = [
            "<a href=\"{0}\">{0}</a>".format(message.attachment)
        ]
        return WacbHtmlFormatter.joinLines(htmlLines)

    def formatAttachmentMessage(self, message):
        attachmentName = message.attachment
        lastDotPos = attachmentName.rfind(".")
        attachmentExt = attachmentName[lastDotPos+1:] if lastDotPos != -1 else None
        if (attachmentExt in ["jpg", "jpeg", "png", "thumb", "webp"]) and self.inlineImages:
            html = self.formatImageAttachmentMessage(message)
        elif (attachmentExt in ["mp4", "mov"]) and self.inlineVideo:
            html = self.formatVideoAttachmentMessage(message)
        elif (attachmentExt in ["mp3", "3gp", "m4a", "opus"]) and self.inlineAudio:
            html = self.formatAudioAttachmentMessage(message)
        else:
            html = self.formatGenericAttachmentMessage(message)
        self.linkedAttachments.add(message.attachment)
        return html

    def formatUserMessage(self, message):
        htmlLines = [
            "<div class=\"message\">",
            "<div class=\"{0} userMessage\">".format(self.getMsgClass(message))
        ]
        html = WacbHtmlFormatter.joinLines(htmlLines)
        html += self.senderId(message)

        if message.hasAttachment:
            html += self.formatAttachmentMessage(message)

        if message.text:
            html += self.formatRegularUserMessage(message)

        htmlLines = [
            "<div class=\"timestamp\">",
            message.time.strftime("%H:%M"),
            "</div>",
            "</div>",
            "</div>",
            "<p>"
        ]
        html += WacbHtmlFormatter.joinLines(htmlLines)
        return html

    def formatSystemMessage(self, message):
        htmlLines = [
            "<div class=\"message\">",
            "<div class=\"systemMessage\">",
            self.formatMessageText(message.text),
            "</div>",
            "</div>",
            "<p>"
        ]
        return WacbHtmlFormatter.joinLines(htmlLines)

    def formatDay(self, date):
        return date.strftime(self.formatForDay)

    def anchorDay(self, year, month, day):
        return "{0:04d}-{1:02d}-{2:02d}".format(year, month, day)

    def linkDay(self, toYear, toMonth, toDay, fromYear=None, fromMonth=None):
        anchor = self.anchorDay(toYear, toMonth, toDay)
        isSameYear = fromYear and (fromYear == toYear)
        isSameMonth = isSameYear and fromMonth and (fromMonth == toMonth)

        if self.config["showAs"] == "Single":
            return "#" + anchor
        elif self.config["showAs"] == "Annual" and isSameYear:
            return "#" + anchor
        elif self.config["showAs"] == "Annual" and not isSameYear:
            link = self.linkYear(toYear, fromYear)
            return link + "#" + anchor
        elif self.config["showAs"] == "Monthly" and isSameMonth:
            return "#" + anchor
        else:
            link = self.linkMonth(toYear, toMonth, fromYear, fromMonth)
            return link + "#" + anchor

    def formatMonth(self, date):
        return date.strftime(self.formatForMonth)

    def anchorMonth(self, year, month):
        return "{0:04d}-{1:02d}".format(year, month)

    def linkMonth(self, toYear, toMonth, fromYear=None, fromMonth=None):
        anchor = self.anchorMonth(toYear, toMonth)
        isSameYear = fromYear and (fromYear == toYear)
        isSameMonth = isSameYear and fromMonth and (fromMonth == toMonth)

        if self.config["showAs"] == "Single":
            return "#" + anchor
        elif self.config["showAs"] == "Annual" and isSameYear:
            return "#" + anchor
        elif self.config["showAs"] == "Annual" and not isSameYear:
            link = self.linkYear(toYear, fromYear)
            return link + "#" + anchor
        elif self.config["showAs"] == "Monthly" and isSameMonth:
            return "#" + anchor
        else:
            return "{0:04d}-{1:02d}.html".format(toYear, toMonth)

    def formatYear(self, date):
        return date.strftime(self.formatForYear)

    def anchorYear(self, year):
        return "{0:04d}".format(year)

    def linkYear(self, toYear, toMonth, fromYear=None):
        if (fromYear and (fromYear == toYear)) or self.config["showAs"] == "Single":
            return "#{0:04d}".format(toYear)
        elif self.config["showAs"] == "Annual":
            return "{0:04d}.html".format(toYear)
        else:
            return self.linkMonth(toYear, toMonth, fromYear)

    #
    # Generate HTML for navigation headers between messages.
    #
    # E.g., if the previous message is from December 31, 1999, and the next one
    # is from January 1, 2000, then we print "<h1>2000</h1>" between them.
    #

    def navigationHeaders(self, lastTimestamp, thisTimestamp):
        htmlLines = []
        if not lastTimestamp or lastTimestamp.year != thisTimestamp.year:
            lastTimestamp = None

            yearAnchor = self.anchorYear(thisTimestamp.year)
            htmlLines.append("<h1 id=\"" + yearAnchor + "\">")

            prevYear = self.messageContainer.calendar.getPrevYear(thisTimestamp.year)
            prevMonth = self.messageContainer.calendar.getFirstMonth(prevYear)[1]

            if prevYear:
                prevYearLink = self.linkYear(prevYear, prevMonth, thisTimestamp.year)
                htmlLines.append("<a href=\"" + prevYearLink + "\">&lt;</a>")

            yearFormatted = self.formatYear(thisTimestamp)
            htmlLines.append(yearFormatted)

            nextYear = self.messageContainer.calendar.getNextYear(thisTimestamp.year)
            nextMonth = self.messageContainer.calendar.getFirstMonth(nextYear)[1]

            if nextYear:
                nextYearLink = self.linkYear(nextYear, nextMonth, thisTimestamp.year)
                htmlLines.append("<a href=\"" + nextYearLink + "\">&gt;</a>")

            htmlLines.append("</h1>")

        if not lastTimestamp or lastTimestamp.month != thisTimestamp.month:
            lastTimestamp = None

            monthAnchor = self.anchorMonth(thisTimestamp.year, thisTimestamp.month)
            htmlLines.append("<h2 id=\"" + monthAnchor + "\">")

            firstMonth = self.messageContainer.calendar.getFirstMonth(thisTimestamp.year)[1]
            thisYearLink = self.linkYear(thisTimestamp.year, firstMonth, thisTimestamp.year)
            htmlLines.append("<a href=\"" + thisYearLink + "\">&lt;&lt;</a>")

            prevYear, prevMonth = self.messageContainer.calendar.getPrevMonth(thisTimestamp.year, thisTimestamp.month)
            if prevMonth:
                prevMonthLink = self.linkMonth(prevYear, prevMonth, thisTimestamp.year, thisTimestamp.month)
                htmlLines.append("<a href=\"" + prevMonthLink + "\">&lt;</a>")

            monthFormatted = self.formatMonth(thisTimestamp)
            htmlLines.append(monthFormatted)

            nextYear, nextMonth = self.messageContainer.calendar.getNextMonth(thisTimestamp.year, thisTimestamp.month)
            if nextMonth:
                nextMonthLink = self.linkMonth(nextYear, nextMonth, thisTimestamp.year, thisTimestamp.month)
                htmlLines.append("<a href=\"" + nextMonthLink + "\">&gt;</a>")

            nextYear = self.messageContainer.calendar.getNextYear(thisTimestamp.year)
            firstMonth = self.messageContainer.calendar.getFirstMonth(nextYear)[1]
            if nextYear:
                nextYearLink = self.linkYear(nextYear, firstMonth, thisTimestamp.year)
                htmlLines.append("<a href=\"" + nextYearLink + "\">&gt;&gt;</a>")

            htmlLines.append("</h2>")

        if not lastTimestamp or lastTimestamp.day != thisTimestamp.day:
            htmlLines.append("<hr>")

            dayAnchor = self.anchorDay(thisTimestamp.year, thisTimestamp.month, thisTimestamp.day)
            htmlLines.append("<h3 id=\"" + dayAnchor + "\">")

            thisMonthLink = self.linkMonth(thisTimestamp.year, thisTimestamp.month, thisTimestamp.year, thisTimestamp.month)
            htmlLines.append("<a href=\"" + thisMonthLink + "\">&lt;&lt;</a>")

            prevYear, prevMonth, prevDay = self.messageContainer.calendar.getPrevDay(thisTimestamp.year, thisTimestamp.month, thisTimestamp.day)
            if prevDay:
                prevDayLink = self.linkDay(prevYear, prevMonth, prevDay, thisTimestamp.year, thisTimestamp.month)
                htmlLines.append("<a href=\"" + prevDayLink + "\">&lt;</a>")

            dayFormatted = self.formatDay(thisTimestamp)
            htmlLines.append(dayFormatted)

            nextYear, nextMonth, nextDay = self.messageContainer.calendar.getNextDay(thisTimestamp.year, thisTimestamp.month, thisTimestamp.day)
            if nextDay:
                nextDayLink = self.linkDay(nextYear, nextMonth, nextDay, thisTimestamp.year, thisTimestamp.month)
                htmlLines.append("<a href=\"" + nextDayLink + "\">&gt;</a>")

            nextYear, nextMonth = self.messageContainer.calendar.getNextMonth(thisTimestamp.year, thisTimestamp.month)
            if nextMonth:
                nextMonthLink = self.linkMonth(nextYear, nextMonth, thisTimestamp.year, thisTimestamp.month)
                htmlLines.append("<a href=\"" + nextMonthLink + "\">&gt;&gt;</a>")

            htmlLines.append("</h3>")
            htmlLines.append("<hr>")

        return WacbHtmlFormatter.joinLines(htmlLines)

    #
    # Takes one message and returns its HTML.
    #

    def formatMessage(self, message):
        if message.isSystemMessage:
            html = self.formatSystemMessage(message)
        else:
            html = self.formatUserMessage(message)
        return html

    #
    # Writes a full HTML document with all messages to the output file.
    #

    def generateMessagesDocument(self, outputFile, fromDate=None, toDate=None):
        html = self.htmlHeader()
        outputFile.write(html.encode())

        if fromDate:
            firstIndex = self.messageContainer.findByTimestamp(fromDate)
        else:
            firstIndex = 0

        if firstIndex == 0:
            lastMessageTimestamp = None
        else:
            lastMessageTimestamp = self.messageContainer[firstIndex-1].time

        if firstIndex >= len(self.messageContainer):
            html = "<b>No messages.</b>"
            outputFile.write(html.encode())

        for index in range(firstIndex, len(self.messageContainer)):
            message = self.messageContainer[index]
            if toDate and message.time.date() >= toDate:
                break
            html = self.navigationHeaders(lastMessageTimestamp, message.time)
            outputFile.write(html.encode())
            html = self.formatMessage(message)
            outputFile.write(html.encode())
            lastMessageTimestamp = message.time

        html = self.htmlFooter()
        outputFile.write(html.encode())

    def generateSinglePage(self, outputFile):
        self.generateMessagesDocument(outputFile)

    def generateAnnualPage(self, outputFile, year):
        fromDate = datetime.date(year, 1, 1)
        toDate = datetime.date(year+1, 1, 1)
        self.generateMessagesDocument(outputFile, fromDate, toDate)

    def generateMonthlyPage(self, outputFile, year, month):
        fromDate = datetime.date(year, month, 1)
        if month < 12:
            toDate = datetime.date(year, month+1, 1)
        else:
            toDate = datetime.date(year+1, 1, 1)
        self.generateMessagesDocument(outputFile, fromDate, toDate)

    #
    # Generate HTML for a navigation index.
    #
    #

    def navigationIndex(self, lastTimestamp, thisTimestamp):
        htmlLines = []

        if not thisTimestamp:
            if lastTimestamp:
                htmlLines.append("</dd>")
                htmlLines.append("</dl>")
            return WacbHtmlFormatter.joinLines(htmlLines)

        if lastTimestamp:
            differentYear = lastTimestamp.year != thisTimestamp.year
            differentMonth = differentYear or (lastTimestamp.month != thisTimestamp.month)
            differentDay = differentMonth or (lastTimestamp.day != thisTimestamp.day)
        else:
            differentYear = True
            differentMonth = True
            differentDay = True

        if differentMonth:
            if lastTimestamp:
                htmlLines.append("</dd>")

        if differentYear:
            if lastTimestamp:
                htmlLines.append("</dl>")
            htmlLines.append("<h1>")
            htmlLines.append("<a href=\"" + self.linkYear(thisTimestamp.year, thisTimestamp.month) + "\">")
            htmlLines.append(self.formatYear(thisTimestamp))
            htmlLines.append("</a>")
            htmlLines.append("</h1>")
            htmlLines.append("<dl>")

        if differentMonth:
            htmlLines.append("<dt>")
            htmlLines.append("<a href=\"" + self.linkMonth(thisTimestamp.year, thisTimestamp.month) + "\">")
            htmlLines.append(self.formatMonth(thisTimestamp))
            htmlLines.append("</a>")
            htmlLines.append("</dt>")
            htmlLines.append("<dd>")

        if differentDay:
            htmlLines.append("<a href=\"" + self.linkDay(thisTimestamp.year, thisTimestamp.month, thisTimestamp.day) + "\">")
            htmlLines.append("{:2d} ".format(thisTimestamp.day))
            htmlLines.append("</a>")

        return WacbHtmlFormatter.joinLines(htmlLines)

    #
    # Write an index.
    #

    def generateNavigationIndex(self, outputFile):
        html = self.htmlHeader()
        outputFile.write(html.encode())

        lastMessageTimestamp = None
        for message in self.messageContainer:
            html = self.navigationIndex(lastMessageTimestamp, message.time)
            outputFile.write(html.encode())
            lastMessageTimestamp = message.time

        if not lastMessageTimestamp:
            html = "<b>No messages.</b>"
            outputFile.write(html.encode())

        html = self.navigationIndex(lastMessageTimestamp, None)
        outputFile.write(html.encode())
        html = self.htmlFooter()
        outputFile.write(html.encode())

    #
    # Write the CSS document.
    #

    def generateCss(self, outputFile, updatecb=None):
        if not self.css:
            raise Exception("Oops.")
        data = self.css.data.encode()
        outputFile.write(data)
        if updatecb:
            updatecb.update(len(data))

    #
    # Generate a HTML page.
    #

    def generateHtml(self, url, outputFile, updatecb=None):
        oops = False
        fileNameMatch = WacbHtmlFormatter.regexForFileName.match(url)

        if url == "/index.html" or url == "index.html":
            if (self.config["showAs"] == "Annual") or (self.config["showAs"] == "Monthly"):
                self.generateNavigationIndex(outputFile)
            else:
                self.generateSinglePage(outputFile)
        elif self.config["showAs"] == "Annual":
            if fileNameMatch and fileNameMatch[1]:
                year = int(fileNameMatch[1])
                self.generateAnnualPage(outputFile, year)
            else:
                oops = True
        elif self.config["showAs"] == "Monthly":
            if fileNameMatch and fileNameMatch[1] and fileNameMatch[2]:
                year = int(fileNameMatch[1])
                month = int(fileNameMatch[2])
                self.generateMonthlyPage(outputFile, year, month)
            else:
                oops = True
        else:
            oops = True

        if oops:
            html = self.htmlHeader()
            outputFile.write(html.encode())

            html = "<b>Oops.</b>"
            outputFile.write(html.encode())

            html = self.htmlFooter()
            outputFile.write(html.encode())

    #
    # Do I feel responsible for this URL?
    #

    def isCssUrl(self, url):
        return self.css and ((url == WacbHtmlFormatter.cssUrl) or (url[1:] == WacbHtmlFormatter.cssUrl))

    def isHtmlUrl(self, url):
        return url.endswith(".html")

    def hasFile(self, path):
        return self.isCssUrl(path) or self.isHtmlUrl(path)

    def getFileSize(self, path):
        return -1

    def copyFile(self, path, outputFile, updatecb=None):
        if self.css and self.isCssUrl(path):
            self.generateCss(outputFile, updatecb)
        elif self.isHtmlUrl(path):
            self.generateHtml(path, outputFile, updatecb)
        else:
            raise Exception("Oops.")

    def enumerateUrls(self):
        urls = ["index.html", WacbHtmlFormatter.cssUrl]
        if self.config["showAs"] == "Annual":
            year = self.messageContainer.calendar.getFirstYear()
            while year:
                urls.append(self.linkYear(year, None))
                year = self.messageContainer.calendar.getNextYear(year)
        elif self.config["showAs"] == "Monthly":
            year, month = self.messageContainer.calendar.getFirstMonth()
            while year:
                urls.append(self.linkMonth(year, month))
                year, month = self.messageContainer.calendar.getNextMonth(year, month)
        return urls

